# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pyproject.toml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: setup environment
          command: |
            export PYTHONPATH=$(pwd):$(pwd)/src
            echo "Current PYTHONPATH is:"
            echo $PYTHONPATH
            echo "Current directory:"
            ls -alh
      - run:
          name: install dependencies
          command: |
            python3.7 -m venv venv
            source venv/bin/activate
            pip install poetry
            poetry install --no-interaction --no-ansi
      - run:
          name: lint with flake8
          command: flake8 src/testmon/*
      - run:
          name: lint with pylint
          command: pylint src/testmon/*
      - run:
          name: bandit static analysis
          command: bandit -r src/testmon/*
      - run:
          name: run tests
          command: pytest tests/*
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "pyproject.toml" }}
      - store_artifacts:
          path: test-reports
          destination: test-reports